import { displayDigitBytesLength } from '../data/status-bar-display-digit-layout.js';
import type { GameRam } from './types.js';

const METATILE_ROWS = 13;
const BLOCK_BUFFER_BYTES = 16 * 13;

export function createGameRam(): GameRam {
  return {
    worldNumber: 0,
    areaNumber: 0,
    areaPointer: 0,
    areaType: 0,
    areaAddrsLowOffset: 0,
    areaObjectBytes: new Uint8Array(0),
    enemyObjectBytes: new Uint8Array(0),
    areaDataOffset: 0,
    metatileBuffer: new Uint8Array(METATILE_ROWS),
    blockBuffer1: new Uint8Array(BLOCK_BUFFER_BYTES),
    blockBuffer2: new Uint8Array(BLOCK_BUFFER_BYTES),
    currentColumnPos: 0,
    currentPageLoc: 0,
    blockBufferColumnPos: 0,
    backgroundScenery: 0,
    foregroundScenery: 0,
    terrainControl: 0,
    cloudTypeOverride: 0,
    areaStyle: 0,
    backgroundColorCtrl: 0,
    playerEntranceCtrl: 0,
    gameTimerSetting: 0,
    displayDigitBytes: new Uint8Array(displayDigitBytesLength),
    digitModifierScratch: new Uint8Array(7),
    gameTimerCtrlTimer: 0,
    fetchNewGameTimerFlag: 1,
    gameTimerExpiredFlag: 0,
    operMode: 1,
    playerStatus: 0,
    areaObjectLengthSlots: new Uint8Array([0xff, 0xff, 0xff]),
    areaObjectOffsetBuffer: new Uint8Array(3),
    areaObjectPageLoc: 0,
    areaObjectPageSel: 0,
    behindAreaParserFlag: 0,
    objectOffset: 0,
    backloadingFlag: 0,
    loopCommand: 0,
    scratchObjectBits: 0,
    objectRowIndex: 0,
    areaObjectDecoderAddend: 0,
    hiddenOneUpFlag: 0,
    staircaseControl: 0,
    mushroomLedgeHalfLengthSlots: new Uint8Array(3),
    cannonOffset: 0,
    whirlpoolOffset: 0,
    enemyFlagSlots: new Uint8Array(5),
    primaryHardMode: 0,
    halfwayPage: 0,
    verticalObjectScratch: 0,
    marioSizeCode: 1,
    marioPowerupTier: 0,
    crouchingFlag: 0,
    playerState: 0,
    playerPageLoc: 0,
    playerXPx: 48,
    playerXSpeed: 0,
    playerHorizontalMoveForce: 0,
    playerXSpeedAbsolute: 0,
    frictionAdderHigh: 0,
    frictionAdderLow: 0,
    maximumLeftSpeed: 0,
    maximumRightSpeed: 0,
    runningSpeed: 0,
    runningTimer: 0,
    playerFacingDir: 1,
    playerMovingDir: 1,
    playerYPx: 176,
    playerYHighPos: 1,
    playerYSpeed: 0,
    playerYMoveForce: 0,
    playerYMoveForceDummy: 0,
    verticalForce: 0x70,
    verticalForceDown: 0x70,
    jumpSwimTimer: 0,
    jumpOriginYPosition: 0,
    jumpOriginYHighPos: 0,
    diffToHaltJump: 1,
    gameEngineSubroutine: 8,
    playerCollisionBits: 0xff,
    playerChangeSizeFlag: 0,
    swimmingFlag: 0,
    disableCollisionDetection: 0,
    blockBounceTimer: 0,
    sideCollisionTimer: 0,
    jumpspringAnimCtrl: 0,
    timerControl: 0,
    playerAnimTimer: 8,
    playerAnimTimerSet: 0,
    playerAnimFrame: 0,
    savedJoypadBits: 0,
    previousAbJoypadBits: 0,
    debugSuperToggleRequest: 0,
  };
}
