/**
 * One-shot extraction of the 8 KB CHR-ROM from docs/data/smb.nes into the
 * string-grid format used by src/data/chr-tiles.ts. Run once, redirect into
 * src/data/chr-tiles.ts, commit.
 *
 * Usage:
 *   node scripts/extract-chr-from-rom.ts > src/data/chr-tiles.ts
 *
 * Per ADR-0004: the runtime never touches CHR-ROM bytes — this script's
 * output (256 hand-readable string-grid tiles) is what gets committed.
 * Named demo tile indices live in src/data/demo-tile-slots.ts (not here).
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const INES_HEADER_BYTES = 16;
const PRG_ROM_BYTES = 32 * 1024;
const CHR_ROM_OFFSET = INES_HEADER_BYTES + PRG_ROM_BYTES;
const CHR_ROM_BYTES = 8 * 1024;
const TILE_BYTES = 16;
const TILE_PX = 8;
const TILE_COUNT = CHR_ROM_BYTES / TILE_BYTES;

type TileRow = string;
type TilePixels = readonly [TileRow, TileRow, TileRow, TileRow, TileRow, TileRow, TileRow, TileRow];

function decodeChrTile(romBytes: Uint8Array, byteOffset: number): TilePixels {
  const rows: TileRow[] = [];

  for (let y = 0; y < TILE_PX; y++) {
    const plane0 = romBytes[byteOffset + y];
    const plane1 = romBytes[byteOffset + y + TILE_PX];
    let row = '';

    for (let x = 0; x < TILE_PX; x++) {
      const shift = 7 - x;
      const bit0 = (plane0 >> shift) & 1;
      const bit1 = (plane1 >> shift) & 1;
      row += String(bit0 | (bit1 << 1));
    }

    rows.push(row);
  }

  return rows as unknown as TilePixels;
}

function decodeChrRom(romBytes: Uint8Array): TilePixels[] {
  const tiles: TilePixels[] = [];

  for (let i = 0; i < TILE_COUNT; i++) {
    const offset = CHR_ROM_OFFSET + i * TILE_BYTES;
    tiles.push(decodeChrTile(romBytes, offset));
  }

  return tiles;
}

function formatTileLiteral(tile: TilePixels): string {
  const quoted = tile.map((row) => `'${row}'`).join(', ');
  return `[${quoted}]`;
}

function generateChrTilesSource(tiles: TilePixels[]): string {
  const lines: string[] = [];

  lines.push('/**');
  lines.push(' * CHR tile pixel data (per ADR-0004).');
  lines.push(' *');
  lines.push(" * Each tile is an 8-row string grid. Each char is a palette index '0'..'3'.");
  lines.push(" * '0' is the area's backdrop; '1'..'3' are the three other colours of the");
  lines.push(' * sub-palette chosen at draw time.');
  lines.push(' *');
  lines.push(' * Tile slot ordering (the index in `chrTiles`) is the value passed to the');
  lines.push(' * tile renderer. Readable names for the scroll demo live in');
  lines.push(' * src/data/demo-tile-slots.ts.');
  lines.push(' *');
  lines.push(' * This file is generated by scripts/extract-chr-from-rom.ts. Do not edit');
  lines.push(' * the pixel grids by hand — re-run the script after replacing');
  lines.push(' * docs/data/smb.nes with a valid SMB1 iNES dump.');
  lines.push(' */');
  lines.push('');
  lines.push('export type TilePixels = readonly [string, string, string, string, string, string, string, string];');
  lines.push('');
  lines.push('export const chrTiles: readonly TilePixels[] = [');

  for (const tile of tiles) {
    lines.push(`  ${formatTileLiteral(tile)},`);
  }

  lines.push('];');
  lines.push('');

  return lines.join('\n');
}

function main(): void {
  const romPath = resolve(process.cwd(), 'docs/data/smb.nes');
  const romBytes = new Uint8Array(readFileSync(romPath));

  if (romBytes.length < CHR_ROM_OFFSET + CHR_ROM_BYTES) {
    throw new Error(`ROM at ${romPath} is too small (${romBytes.length} bytes); expected at least ${CHR_ROM_OFFSET + CHR_ROM_BYTES}`);
  }

  const tiles = decodeChrRom(romBytes);
  process.stdout.write(generateChrTilesSource(tiles));
}

main();
