/**
 * Extract level/enemy/metatile tables from SMBDIS.ASM into committed TypeScript
 * modules under src/data/extracted/.
 *
 * Pointer tables that use assembler relocations (<label, label-label) are taken
 * from the US PRG-ROM at a fixed anchor verified against smb.nes.
 *
 * Usage:
 *   npx tsx scripts/extract-level-tables-from-asm.ts
 *
 * Inputs (repo defaults):
 *   docs/data/SMBDIS.ASM
 *   docs/data/smb.nes
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');

const SMBDIS_PATH = resolve(REPO_ROOT, 'docs/data/SMBDIS.ASM');
const ROM_PATH = resolve(REPO_ROOT, 'docs/data/smb.nes');
const OUT_DIR = resolve(REPO_ROOT, 'src/data/extracted');

/** PRG offset of WorldAddrOffsets in verified US SMB1 iNES dump (16-byte header). */
const PRG_WORLD_AREA_POINTERS_OFFSET = 0x1cb4;
const POINTER_BLOCK_LENGTH = 188;

function readPrgRom(): Uint8Array {
  const rom = readFileSync(ROM_PATH);
  const header = 16;
  const prgSize = 32768;
  if (rom.length < header + prgSize) {
    throw new Error(`ROM too small: ${ROM_PATH}`);
  }
  return rom.subarray(header, header + prgSize);
}

function parseDbOperands(segment: string): number[] {
  const beforeComment = segment.split(';')[0] ?? '';
  const bytes: number[] = [];

  for (let raw of beforeComment.split(',')) {
    raw = raw.trim();
    if (raw.length === 0) {
      continue;
    }

    const dbMatch = raw.match(/^\.db\s+/i);
    if (dbMatch) {
      raw = raw.slice(dbMatch[0].length).trim();
    }

    const hex = raw.match(/^\$([0-9a-f]{2})$/i);
    if (hex) {
      bytes.push(Number.parseInt(hex[1], 16));
      continue;
    }

    const bin = raw.match(/^%([01]{8})$/);
    if (bin) {
      bytes.push(Number.parseInt(bin[1], 2));
      continue;
    }

    throw new Error(`Unsupported operand (use hex/binary only): ${raw}`);
  }

  return bytes;
}

function extractAsmDbLabel(asm: string, label: string): Uint8Array {
  const lines = asm.split(/\r?\n/);
  const bytes: number[] = [];
  let capturing = false;
  const labelStart = new RegExp(`^${label}\\s*:`);

  for (const rawLine of lines) {
    const codePart = rawLine.split(';')[0] ?? '';
    const trimmedStart = codePart.trimStart();

    if (!capturing) {
      if (labelStart.test(trimmedStart)) {
        capturing = true;
        const afterColon = trimmedStart.replace(/^[^:]+:\s*/, '');
        if (/\.db\b/i.test(afterColon)) {
          bytes.push(...parseDbOperands(afterColon));
        }
      }
      continue;
    }

    const labelMatch = trimmedStart.match(/^([A-Za-z_][\w]*)\s*:/);
    if (labelMatch && labelMatch[1] !== label) {
      break;
    }

    if (/^\s*\.db\b/i.test(codePart)) {
      bytes.push(...parseDbOperands(codePart));
    }
  }

  if (!capturing) {
    throw new Error(`Label not found: ${label}`);
  }

  return Uint8Array.from(bytes);
}

function emitUint8Module(exports: { name: string; data: Uint8Array }[]): string {
  const lines: string[] = [];

  lines.push('/**');
  lines.push(' * Generated by scripts/extract-level-tables-from-asm.ts — do not edit.');
  lines.push(' */');
  lines.push('');

  for (const { name, data } of exports) {
    lines.push(`export const ${name} = new Uint8Array([`);
    lines.push(
      `  ${Array.from(data)
        .map((b) => `0x${b.toString(16).padStart(2, '0')}`)
        .join(', ')},`,
    );
    lines.push(']);');
    lines.push('');
  }

  return lines.join('\n');
}

function slicePointerBlock(prg: Uint8Array): {
  worldAddrOffsets: Uint8Array;
  areaAddrOffsets: Uint8Array;
  enemyAddrHighOffsets: Uint8Array;
  enemyDataAddrLow: Uint8Array;
  enemyDataAddrHigh: Uint8Array;
  areaDataHighOffsets: Uint8Array;
  areaDataAddrLow: Uint8Array;
  areaDataAddrHigh: Uint8Array;
} {
  const blob = prg.subarray(PRG_WORLD_AREA_POINTERS_OFFSET, PRG_WORLD_AREA_POINTERS_OFFSET + POINTER_BLOCK_LENGTH);
  if (blob.length !== POINTER_BLOCK_LENGTH) {
    throw new Error('Pointer block length mismatch');
  }

  let o = 0;
  const worldAddrOffsets = blob.subarray(o, o + 8);
  o += 8;
  const areaAddrOffsets = blob.subarray(o, o + 36);
  o += 36;
  const enemyAddrHighOffsets = blob.subarray(o, o + 4);
  o += 4;
  const enemyDataAddrLow = blob.subarray(o, o + 34);
  o += 34;
  const enemyDataAddrHigh = blob.subarray(o, o + 34);
  o += 34;
  const areaDataHighOffsets = blob.subarray(o, o + 4);
  o += 4;
  const areaDataAddrLow = blob.subarray(o, o + 34);
  o += 34;
  const areaDataAddrHigh = blob.subarray(o, o + 34);
  o += 34;

  if (o !== POINTER_BLOCK_LENGTH) {
    throw new Error('Pointer block slice arithmetic drifted');
  }

  return {
    worldAddrOffsets,
    areaAddrOffsets,
    enemyAddrHighOffsets,
    enemyDataAddrLow,
    enemyDataAddrHigh,
    areaDataHighOffsets,
    areaDataAddrLow,
    areaDataAddrHigh,
  };
}

function main(): void {
  mkdirSync(OUT_DIR, { recursive: true });

  const asm = readFileSync(SMBDIS_PATH, 'utf8');
  const prg = readPrgRom();
  const pointers = slicePointerBlock(prg);

  const levelLabels = [
    'L_CastleArea1',
    'L_CastleArea2',
    'L_CastleArea3',
    'L_CastleArea4',
    'L_CastleArea5',
    'L_CastleArea6',
    'L_GroundArea1',
    'L_GroundArea2',
    'L_GroundArea3',
    'L_GroundArea4',
    'L_GroundArea5',
    'L_GroundArea6',
    'L_GroundArea7',
    'L_GroundArea8',
    'L_GroundArea9',
    'L_GroundArea10',
    'L_GroundArea11',
    'L_GroundArea12',
    'L_GroundArea13',
    'L_GroundArea14',
    'L_GroundArea15',
    'L_GroundArea16',
    'L_GroundArea17',
    'L_GroundArea18',
    'L_GroundArea19',
    'L_GroundArea20',
    'L_GroundArea21',
    'L_GroundArea22',
    'L_UndergroundArea1',
    'L_UndergroundArea2',
    'L_UndergroundArea3',
    'L_WaterArea1',
    'L_WaterArea2',
    'L_WaterArea3',
  ] as const;

  const enemyLabels = [
    'E_CastleArea1',
    'E_CastleArea2',
    'E_CastleArea3',
    'E_CastleArea4',
    'E_CastleArea5',
    'E_CastleArea6',
    'E_GroundArea1',
    'E_GroundArea2',
    'E_GroundArea3',
    'E_GroundArea4',
    'E_GroundArea5',
    'E_GroundArea6',
    'E_GroundArea7',
    'E_GroundArea8',
    'E_GroundArea9',
    'E_GroundArea10',
    'E_GroundArea11',
    'E_GroundArea12',
    'E_GroundArea13',
    'E_GroundArea14',
    'E_GroundArea15',
    'E_GroundArea16',
    'E_GroundArea17',
    'E_GroundArea18',
    'E_GroundArea19',
    'E_GroundArea20',
    'E_GroundArea21',
    'E_GroundArea22',
    'E_UndergroundArea1',
    'E_UndergroundArea2',
    'E_UndergroundArea3',
    'E_WaterArea1',
    'E_WaterArea2',
    'E_WaterArea3',
  ] as const;

  const dictionaryLabels = [
    'BSceneDataOffsets',
    'BackSceneryData',
    'BackSceneryMetatiles',
    'ForeSceneryData',
    'FSceneDataOffsets',
    'TerrainMetatiles',
    'TerrainRenderBits',
    'BrickMetatiles',
    'SolidBlockMetatiles',
    'CastleMetatiles',
    'BlockBuffLowBounds',
    'HoleMetatiles',
    'PulleyRopeMetatiles',
    'BrickQBlockMetatiles',
    'VerticalPipeData',
    'SidePipeShaftData',
    'SidePipeTopPart',
    'SidePipeBottomPart',
    'StaircaseHeightData',
    'StaircaseRowData',
    'CoinMetatileData',
    'C_ObjectRow',
    'C_ObjectMetatile',
  ] as const;

  const paletteLabels = ['Palette0_MTiles', 'Palette1_MTiles', 'Palette2_MTiles', 'Palette3_MTiles'] as const;

  const bitmaskLabel = 'Bitmasks';

  const levelExports = levelLabels.map((label) => ({
    name: label,
    data: extractAsmDbLabel(asm, label),
  }));

  const enemyExports = enemyLabels.map((label) => ({
    name: label,
    data: extractAsmDbLabel(asm, label),
  }));

  const dictionaryExports = dictionaryLabels.map((label) => ({
    name: label,
    data: extractAsmDbLabel(asm, label),
  }));

  const paletteExports = paletteLabels.map((label) => ({
    name: label,
    data: extractAsmDbLabel(asm, label),
  }));

  const bitmaskExport = {
    name: bitmaskLabel,
    data: extractAsmDbLabel(asm, bitmaskLabel),
  };

  writeFileSync(
    resolve(OUT_DIR, 'world-area-pointers.ts'),
    emitUint8Module([
      { name: 'worldAddrOffsets', data: pointers.worldAddrOffsets },
      { name: 'areaAddrOffsets', data: pointers.areaAddrOffsets },
      { name: 'enemyAddrHighOffsets', data: pointers.enemyAddrHighOffsets },
      { name: 'enemyDataAddrLow', data: pointers.enemyDataAddrLow },
      { name: 'enemyDataAddrHigh', data: pointers.enemyDataAddrHigh },
      { name: 'areaDataHighOffsets', data: pointers.areaDataHighOffsets },
      { name: 'areaDataAddrLow', data: pointers.areaDataAddrLow },
      { name: 'areaDataAddrHigh', data: pointers.areaDataAddrHigh },
    ]),
  );

  writeFileSync(resolve(OUT_DIR, 'levels.ts'), emitUint8Module(levelExports));
  writeFileSync(resolve(OUT_DIR, 'enemies.ts'), emitUint8Module(enemyExports));
  writeFileSync(resolve(OUT_DIR, 'metatile-dictionaries.ts'), emitUint8Module([...dictionaryExports, bitmaskExport]));

  writeFileSync(resolve(OUT_DIR, 'palette-mtiles.ts'), emitUint8Module(paletteExports));

  // eslint-disable-next-line no-console -- CLI feedback
  console.log(`Wrote extracted tables to ${OUT_DIR}`);
}

main();
